[phases.setup]
nixPkgs = [
  "pango",
  "harfbuzz",
  "glib",
  "gdk-pixbuf",
  "libffi",
  "cairo",
  "fontconfig",
  "freetype",
  "zlib",
]

[start]
cmd = "uvicorn src.main:app --host 0.0.0.0 --port $PORT"
